apiVersion: v1
kind: ConfigMap
metadata:
  name: loopool-app
data:
  # property-like keys; each key maps to a simple value
#  player_initial_lives: "3"
#  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  application.properties: |
    mainDbConnectionString=mongodb://192.168.49.2:27017/loopool
    sysDbConnectionString=mongodb://192.168.49.2:27017/loopool-system
    useMinifiedJS=false
    releaseVersion=0.1.0
    releaseDate=07/09/2023
