apiVersion: v1
kind: Service
metadata:
  name: loopool-command-svc
  labels:
    app: loopool-command
spec:
  ports:
  - port: 30017
    protocol: TCP
    nodePort: 30017
  type: NodePort
  selector:
    app: loopool-command
