apiVersion: v1
kind: Service
metadata:
  name: loopool-query-svc
  labels:
    app: loopool-query
spec:
  ports:
  - port: 30017
    protocol: TCP
    nodePort: 30018
  type: NodePort
  selector:
    app: loopool-query
