apiVersion: v1
kind: ConfigMap
metadata:
  name: loopool-app
  namespace: loopool
data:
  # property-like keys; each key maps to a simple value
#  player_initial_lives: "3"
#  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  application.properties: |
    mainDbConnectionString=mongodb://loopool-cosmos:xQVKzUm4GwaQ0ZeafecxOVtylmmsLT1oXGHw7P6caSAaCIHqDcgHHrXQThpgoQ6mqfJKUhTA3mJJACDbaCby9A==@loopool-cosmos.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&appName=@loopool-cosmos@:27017/loopool
    sysDbConnectionString=mongodb://loopool-cosmos:xQVKzUm4GwaQ0ZeafecxOVtylmmsLT1oXGHw7P6caSAaCIHqDcgHHrXQThpgoQ6mqfJKUhTA3mJJACDbaCby9A==@loopool-cosmos.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&appName=@loopool-cosmos@:27017/loopool-system
    useMinifiedJS=false
    releaseVersion=0.2.0
    releaseDate=08/21/2023
