apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loopool-ingress
  namespace: loopool
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: loopool-command.b371841a981b4f6ab18a.westus3.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loopool-command-svc
            port:
              number: 80
  - host: loopool-query.b371841a981b4f6ab18a.westus3.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loopool-query-svc
            port:
              number: 80